FROM node:18-alpine
WORKDIR /react-docker-example/
COPY node_modules/  /react-docker-example/node_modules
COPY public/ /react-docker-example/public
COPY src/ /react-docker-example/src
COPY package-lock.json /react-docker-example/
COPY package.json /react-docker-example/
COPY README.md /react-docker-example/
RUN npm install
CMD ["npm", "start"]
